// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ControllerApplyKernelConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['ControllerApplyKernelConfig'](arg1, arg2, arg3);
}

export function ControllerGetKernelConfig(arg1) {
  return window['go']['main']['App']['ControllerGetKernelConfig'](arg1);
}

export function ControllerGetKernelRuntimeStats(arg1) {
  return window['go']['main']['App']['ControllerGetKernelRuntimeStats'](arg1);
}

export function ControllerResetKernelRuntimeStats(arg1) {
  return window['go']['main']['App']['ControllerResetKernelRuntimeStats'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateKernelProfile(arg1) {
  return window['go']['main']['App']['CreateKernelProfile'](arg1);
}

export function DeleteKernelProfile(arg1) {
  return window['go']['main']['App']['DeleteKernelProfile'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetKernelControllerState(arg1) {
  return window['go']['main']['App']['GetKernelControllerState'](arg1);
}

export function GetKernelProfiles() {
  return window['go']['main']['App']['GetKernelProfiles']();
}

export function ListKernelProfileRevisions(arg1) {
  return window['go']['main']['App']['ListKernelProfileRevisions'](arg1);
}

export function GetKernelRuntimeStats(arg1) {
  return window['go']['main']['App']['GetKernelRuntimeStats'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadKernelConfig() {
  return window['go']['main']['App']['LoadKernelConfig']();
}

export function LoadKernelProfile(arg1) {
  return window['go']['main']['App']['LoadKernelProfile'](arg1);
}

export function ProbeKernelRoute(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ProbeKernelRoute'](arg1, arg2, arg3, arg4, arg5);
}

export function ProbeKernelRouteText(arg1, arg2) {
  return window['go']['main']['App']['ProbeKernelRouteText'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveKernelConfig(arg1) {
  return window['go']['main']['App']['SaveKernelConfig'](arg1);
}

export function SaveKernelProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveKernelProfile'](arg1, arg2);
}

export function RollbackKernelProfile(arg1, arg2) {
  return window['go']['main']['App']['RollbackKernelProfile'](arg1, arg2);
}

export function SetActiveKernelProfile(arg1) {
  return window['go']['main']['App']['SetActiveKernelProfile'](arg1);
}

export function ResetKernelRuntimeStats(arg1) {
  return window['go']['main']['App']['ResetKernelRuntimeStats'](arg1);
}

export function ValidateKernelConfig(arg1, arg2) {
  return window['go']['main']['App']['ValidateKernelConfig'](arg1, arg2);
}
