// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:main.Config):Promise<void>;

export function Disconnect():Promise<void>;

export function LoadConfig():Promise<main.Config>;

export function SaveConfig(arg1:main.Config):Promise<void>;
