// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ControllerApplyKernelConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ControllerGetKernelConfig(arg1:string):Promise<string>;

export function ControllerGetKernelRuntimeStats(arg1:string):Promise<main.KernelRuntimeStats>;

export function ControllerResetKernelRuntimeStats(arg1:string):Promise<main.KernelRuntimeStats>;

export function Connect(arg1:main.Config):Promise<void>;

export function CreateKernelProfile(arg1:string):Promise<void>;

export function DeleteKernelProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetKernelControllerState(arg1:string):Promise<main.KernelControllerState>;

export function GetKernelProfiles():Promise<main.KernelProfileState>;

export function ListKernelProfileRevisions(arg1:string):Promise<Array<main.KernelProfileRevision>>;

export function GetKernelRuntimeStats(arg1:string):Promise<main.KernelRuntimeStats>;

export function LoadConfig():Promise<main.Config>;

export function LoadKernelConfig():Promise<string>;

export function LoadKernelProfile(arg1:string):Promise<string>;

export function ProbeKernelRoute(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<main.KernelRouteProbeResult>;

export function ProbeKernelRouteText(arg1:string,arg2:string):Promise<main.KernelRouteProbeResult>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveKernelConfig(arg1:string):Promise<void>;

export function SaveKernelProfile(arg1:string,arg2:string):Promise<void>;

export function RollbackKernelProfile(arg1:string,arg2:string):Promise<void>;

export function SetActiveKernelProfile(arg1:string):Promise<void>;

export function ResetKernelRuntimeStats(arg1:string):Promise<void>;

export function ValidateKernelConfig(arg1:string,arg2:string):Promise<main.KernelValidationResult>;
